name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build  -f ./windows/Dockerfile -t pyinstaller-windows .

      - name: Run Docker container
        id: run-container
        run: |
          docker run --rm -v $(pwd)/src:/src -v $(pwd)/windows:/windows \
              pyinstaller-windows pyinstaller main.py \
              --onedir --onefile --clean \
              --distpath /windows/dist \
              --workpath /windows/build \
              --specpath /windows 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./windows/dist/main
