name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build  -f ./windows/Dockerfile -t pyinstaller-windows .

      - name: Run Docker container
        id: run-container
        run: docker run --rm -v ${{ github.workspace }}/src:C:\src -v ${{ github.workspace }}/windows:C:\windows pyinstaller-windows cmd /c "pyinstaller main.py --onedir --onefile --clean --distpath /windows/dist --workpath /windows/build --specpath /windows"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./windows/dist/main
